const { git } = require('../src')
;(async () => {
  // const res = await git.pull()
  // console.log(res)
  // const res = await git.clone('https://gitee.com/zhongkuan/lib.git')
  // console.log(res)
  // const user = git.user()
  // console.log(user)
  git.repository()
})()
